spring.primary-datasource.url=jdbc:h2:mem:primarydb
spring.primary-datasource.jdbc-url=jdbc:h2:mem:primarydb
spring.primary-datasource.driver-class-name=org.h2.Driver
spring.primary-datasource.username=sa
spring.primary-datasource.password=password
spring.secondary-datasource.url=jdbc:h2:mem:secondarydb
spring.secondary-datasource.jdbc-url=jdbc:h2:mem:secondarydb
spring.secondary-datasource.driver-class-name=org.h2.Driver
spring.secondary-datasource.username=sa
spring.secondary-datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
